name: 'Africastalking SMS Action'
description: 'Send an SMS from GitHub Actions using Africastalking Programmable SMS'
author: 'Alpha Olomi'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  sandbox:
    description: 'A boolean value allowing you to use sandbox environment'
    required: false
    type: 'boolean'
  AT_API_KEY:
    description: 'Africastalking API Key. Should be stored in environment'
    required: true
  AT_USERNAME:
    description: 'Africastalking Username. Should be stored in environment'
    required: true
  fromPhoneNumber:
    description: 'Sender ID'
    required: true
  toPhoneNumber:
    description: 'One or more phone number(s) to send the message to. Separate multiple numbers with a comma.'
    required: true
  message:
    description: 'The message to send.'
    required: true
outputs:
  messageId:
    description: 'The ID of the message sent.'
runs:
  using: 'node16'
  main: 'dist/index.js'
